OK offset border padding not working but OK and doc

diff --git a/move-to-next-monitor b/move-to-next-monitor
--- a/move-to-next-monitor
+++ b/move-to-next-monitor
@@ -38,16 +38,34 @@ else
 fi
 mydir=$(dirname $me)
 
-# get_monitors output:
+WINDOW_HORZ_MAXED=""
+WINDOW_VERT_MAXED=""
+
+# get_monitors output: See fake_get_monitors
 # LVDS-1 1366 768 0 515
 # OTHER 1280 1024 1366 0
+# Usage: 
+#   get_monitors
+#   get_monitors SCREEN_NUM
 get_monitors() {
   OFFSET_RE="([0-9]+)\+([0-9]+)"
 
-  xrandr | 
-    sed -nr "/ connected / {
-      s/^([^ ]*).*\b([0-9]+)x([0-9]+)\+$OFFSET_RE.*$/\1 \2 \3 \4 \5/ p
-    }"
+  # $1 can number a monitor starting at 0
+  range="p"
+  if [[ ! -z "$1" ]]
+  then
+    range="$(($1+1)) p"
+  fi
+
+  # allow debug without dual screen
+  if [[ "$fake" -eq 1 ]] ; then
+    fake_get_monitors
+  else
+    xrandr | 
+      sed -nr "/ connected / {
+        s/^([^ ]*).*\b([0-9]+)x([0-9]+)\+$OFFSET_RE.*$/\1 \2 \3 \4 \5/ p
+      }"
+  fi | sed -n -e "$range"
 }
 
 fake_get_monitors() {
@@ -55,41 +73,24 @@ fake_get_monitors() {
   echo VGA-1 1280 1024 1366 0
 }
 
-#get_monitors() {
-#  fake_get_monitors
-#}
-
 get_current_window() {
   # current window_id
-  local window_id=`xdotool getactivewindow`
-
-  # Remember if it was maximized.
-  window_horz_maxed=`xprop -id $window_id _NET_WM_STATE \
-    | grep '_NET_WM_STATE_MAXIMIZED_HORZ'`
-  window_vert_maxed=`xprop -id $window_id _NET_WM_STATE \
-    | grep '_NET_WM_STATE_MAXIMIZED_VERT'`
-
-  echo $window_id
+  xdotool getactivewindow
 }
+
 
 window_get_position() {
   local window_id=$1
 
-  # Read window position
-  x=`xwininfo -id $window_id | awk '/Absolute upper-left X:/ { print $4 }'`
-  y=`xwininfo -id $window_id | awk '/Absolute upper-left Y:/ { print $4 }'`
+  local pos=( `xdotool getwindowgeometry $window_id | awk -F '[ ,]+' '/Position:/ { print $3,$4 }'` )
+  local dim=( `xdotool getwindowgeometry $window_id | awk -F '[ x]+' '/Geometry:/ { print $3,$4 }'` )
 
-  # Subtract any offsets caused by panels or window decorations
-  x_offset=`xwininfo -id $window_id \
-    | awk '/Relative upper-left X:/ { print $4 }'`
-  y_offset=`xwininfo -id $window_id \
-    | awk '/Relative upper-left Y:/ { print $4 }'`
+  if [[ "$fake" -eq 1 ]] ; then
+    read sname swidth sheight sxoff syoff <<< $(get_monitors 0)
+    pos[1]=$((${pos[1]} + $syoff))
+  fi
 
-  x=`expr $x - $x_offset`
-  y=`expr $y - $y_offset`
-
-  pos=( `xdotool getwindowgeometry $window_id | awk -F '[ x]+' '/Geometry:/ { print $3,$4 }'` )
-  echo "$x $y ${pos[@]}"
+  echo "${pos[@]} ${dim[@]}"
 }
 
 get_merged_display() {
@@ -100,70 +101,100 @@ get_merged_display() {
 }
 
 compute_window_center() {
-  # array assign
-  local pos=( $@ )
-  echo $((${pos[0]} + (${pos[2]}) / 2)) $((${pos[1]} + (${pos[3]}) / 2))
+  # array assign IFS must contains ' '
+  local wpos=( $@ )
+  echo $((${wpos[0]} + (${wpos[2]}) / 2)) $((${wpos[1]} + (${wpos[3]}) / 2))
 }
 
 window_compute_move() {
   local window_id=$1
 
-  local screens=( $(get_monitors) )
-  local nbscreen=${#screen[@]}
+  local nbscreen=$(get_monitors | wc -l)
   if [[ $nbscreen -eq 1 ]] ; then
     return 1
   fi
 
   local pos=( $(window_get_position $window_id) )
-  local center=( $(compute_window_center ${pos[@]}) )
+  #local center=( $(compute_window_center ${pos[@]}) )
 
-  # we suppose that monitor are ordered
-  # window coordinate and center are given relative to screen 0
+  # off the border padding
+  local padding=24
+
+  local myscreen=$(find_which_monitor ${pos[@]})
+  # multiple var assignment
+  read sname swidth sheight sxoff syoff <<< $(get_monitors $myscreen)
+  #echo $sname $swidth $sheight $sxoff $syoff
+
+  # remove current screen offset
+  local new_x=$((${pos[0]} - $sxoff))
+  local new_y=$((${pos[1]} - $syoff))
+
+  # Compute new position
+  local nexts=$((($myscreen + 1) % $nbscreen))
+
+  # add new screen offset
+  read sname swidth sheight sxoff syoff <<< $(get_monitors $nexts)
+  #echo $sname $swidth $sheight $sxoff $syoff
+  new_x=$(($new_x + $sxoff))
+  new_y=$(($new_y + $syoff))
+
+  # ensure new position is in the screen, if window width and height is not
+  # too big re integrate window in the screen
+
+  # too far on right
+  local maxx=$(($sxoff + $swidth))
+  if [[ $(($new_x + ${pos[2]})) -gt $maxx ]] ; then
+    new_x=$(($maxx - (${pos[2]} + $padding)))
+  fi
+
+  # too far on bottom
+  local maxy=$(($syoff + $sheight))
+  if [[ $(($new_y + ${pos[3]})) -gt $maxy ]] ; then
+    new_y=$(($maxy - (${pos[3]} + $padding)))
+  fi
+
+  # off the screen coorection
+  if [[ $new_x -lt $sxoff ]] ; then
+    new_x=$(($padding + $sxoff))
+  fi
+
+  if [[ $new_y -lt $syoff ]] ; then
+    new_y=$(($padding + $syoff))
+  fi
+
+  echo $new_x $new_y
+}
+
+find_which_monitor() {
+  # array assign IFS must contains ' '
+  local winpos=( $@ )
+  #echo "${winpos[0]} ${winpos[1]} ${winpos[2]} ${winpos[3]}"
+  # Loop through each screen and compare the offset with the window
+  # coordinates.
+  local i=0
+  local monitor
   while read name width height xoff yoff
   do
-    echo $name $width $height $xoff $yoff
-    if [ "${center[0]}" -ge "$xoff" \
-      -a "${center[1]}" -ge "$yoff" \
-      -a "${center[0]}" -lt "$(($xoff+$width))" \
-      -a "${center[1]}" -lt "$(($yoff+$height))" ]
+    #echo MON: $name $width $height $xoff $yoff
+    if [ "${winpos[0]}" -ge "$xoff" \
+      -a "${winpos[1]}" -ge "$yoff" \
+      -a "${winpos[0]}" -lt "$(($xoff+$width))" \
+      -a "${winpos[1]}" -lt "$(($yoff+$height))" ]
     then
       monitor=$name   
+      break
     fi
+    i=$(($i + 1))
   done < <(get_monitors)
-  echo m=$monitor
-  return 
 
-  # current window screen's dimension
-  display_width=`xdotool getdisplaygeometry | cut -d" " -f1`
-  display_height=`xdotool getdisplaygeometry | cut -d" " -f2`
-
-  merge_screen=( $(get_merged_display) )
-
-  # Compute new X position
-  new_x=`expr $x + ${merge_screen[0]}`
-  # Compute new Y position
-  new_y=`expr $y + ${merge_screen[1]}`
-
-  # If we would move off the right-most monitor, we set it to the left one.
-  # We also respect the window's width here: moving a window off more than half its width won't happen.
-  width=`xdotool getwindowgeometry $window_id | awk '/Geometry:/ { print $2 }'|cut -d"x" -f1`
-  if [ `expr $new_x + $width / 2` -gt $screen_width ]; then
-    new_x=`expr $new_x - $screen_width`
-  fi
-
-  height=`xdotool getwindowgeometry $window_id | awk '/Geometry:/ { print $2 }'|cut -d"x" -f2`
-  if [ `expr $new_y + $height / 2` -gt $screen_height ]; then
-    new_y=`expr $new_y - $screen_height`
-  fi
-
-  # Don't move off the left side.
-  if [ $new_x -lt 0 ]; then
-    new_x=0
-  fi
-
-  # Don't move off the bottom
-  if [ $new_y -lt 0 ]; then
-    new_y=0
+  # If we found a monitor, echo it out, otherwise print an error.
+  if [[ ! -z "$monitor" ]]
+  then
+    echo $i
+    return 0
+  else
+    echo "Couldn't find any monitor for the current window." >&2
+    return 1
   fi
 }
 
@@ -171,20 +202,26 @@ main() {
   # current window properties
   window_id=$(get_current_window)
 
+  # Remember if it was maximized.
+  WINDOW_HORZ_MAXED=`xprop -id $window_id _NET_WM_STATE \
+    | grep '_NET_WM_STATE_MAXIMIZED_HORZ'`
+  WINDOW_VERT_MAXED=`xprop -id $window_id _NET_WM_STATE \
+    | grep '_NET_WM_STATE_MAXIMIZED_VERT'`
+
   new_coord=( $(window_compute_move $window_id) )
 
   # Un-maximize current window so that we can move it
   wmctrl -ir $window_id -b remove,maximized_vert,maximized_horz
 
   # Move the window
-  xdotool windowmove $window_id ${new_coord[@]}
+  xdotool windowmove $window_id ${new_coord[0]} ${new_coord[1]}
 
   # Maximize window again, if it was before
-  if [ -n "${window_horz_maxed}" -a -n "${window_vert_maxed}" ]; then
+  if [ -n "${WINDOW_HORZ_MAXED}" -a -n "${WINDOW_VERT_MAXED}" ]; then
     wmctrl -ir $window_id -b add,maximized_vert,maximized_horz
-  elif [ -n  "${window_horz_maxed}" ]; then
+  elif [ -n  "${WINDOW_HORZ_MAXED}" ]; then
     wmctrl -ir $window_id -b add,maximized_horz
-  elif [ -n  "${window_vert_maxed}" ]; then
+  elif [ -n  "${WINDOW_VERT_MAXED}" ]; then
     wmctrl -ir $window_id -b add,maximized_vert
   fi
 }
